server:
  port: 9501
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    jpa:
      database: MySQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update
  profiles:
    active: dev
  application:
    name: micro-serverless-api
  cloud:
    nacos:
      discovery:
        server-addr: 10.30.5.92:8848
feign:
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
